name: geo-tools

services:
  client:
    image: geo-tools-client:0.0.0
    ports:
      - 3000:80
    depends_on:
      - server
      - tileserver

  server:
    image: geo-tools-server:0.0.0
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    gpus: all
    image: ollama/ollama:0.14.2
    ports:
      - 11434:11434
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ./ollama:/root/.ollama

  tileserver:
    image: maptiler/tileserver-gl:v5.5.0
    ports:
      - 8080:8080
    volumes:
      - ./tileserver:/data
