name: geo-tools

services:
  client:
    image: geo-tools-client:0.0.0
    ports:
      - 3000:80

  server:
    image: geo-tools-server:0.0.0
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0

  tileserver:
    image: maptiler/tileserver-gl:v5.5.0
    ports:
      - 8080:8080
    volumes:
      - ./tileserver:/data
